# TensorFlow – czym jest i do czego służy?

**TensorFlow** to jedna z najpopularniejszych bibliotek do uczenia maszynowego i głębokiego uczenia, stworzona i rozwijana przez **Google Brain Team** (premiera w 2015 roku). Jest napisana w **C++**, z interfejsem w **Pythonie**, a także z wersjami dla języków takich jak JavaScript czy Swift.

### Kluczowe cechy

* **Statyczne grafy obliczeń (w oryginalnej wersji)** – model był definiowany jako cały graf, a następnie wykonywany. To dawało dużą wydajność i łatwość optymalizacji, ale początkowo utrudniało debugowanie.
* **Keras jako wysoki poziom** – od TensorFlow 2.0 domyślnie integruje API **Keras**, co bardzo ułatwia budowanie i trenowanie modeli.
* **Wydajność i skalowalność** – TensorFlow jest zoptymalizowany pod kątem dużych modeli i rozproszonych obliczeń (np. na wielu GPU lub w chmurze).
* **Wsparcie dla produkcji** – ma narzędzia takie jak **TensorFlow Serving**, **TensorFlow Lite** (na urządzenia mobilne) i **TensorFlow.js** (w przeglądarce), które ułatwiają wdrażanie modeli.
* **Eager execution** – od TensorFlow 2.0 działa w trybie „na żywo” (dynamicznym), podobnie jak PyTorch, ale wciąż pozwala przełączać się na grafy statyczne dla optymalizacji.

### Do czego jest używany?

* **Deep learning** – trenowanie modeli CNN, RNN, transformerów.
* **Wizja komputerowa** – rozpoznawanie obrazów, detekcja obiektów (często z biblioteką **tf.keras.applications**).
* **Przetwarzanie języka naturalnego (NLP)** – od klasyfikacji tekstów po nowoczesne modele językowe.
* **Duże wdrożenia produkcyjne** – dzięki wsparciu Google Cloud i narzędziom do serwowania modeli.
* **IoT i mobile** – TensorFlow Lite umożliwia uruchamianie modeli na smartfonach, Raspberry Pi czy mikrokontrolerach.

### Dlaczego jest popularny?

TensorFlow był pierwszym dużym, otwartym frameworkiem wspieranym przez gigantyczną firmę (Google), dlatego szybko stał się standardem przemysłowym. Dzięki ogromnemu ekosystemowi i integracji z Kerasem jest szeroko używany zarówno w badaniach, jak i w zastosowaniach komercyjnych.


## TensorFlow 1.x vs TensorFlow 2.x

### TensorFlow 1.x (2015–2019)

* **Statyczny graf obliczeń**: najpierw budujesz cały graf (np. `tf.placeholder`, `tf.Session`), potem go uruchamiasz.
* **Kod mniej „pythoniczny”** – wymagał znajomości specyficznych konstrukcji (`tf.cond`, `tf.while_loop`) zamiast zwykłych `if` i `for`.
* **Trudniejsze debugowanie** – bo graf był wykonywany dopiero w sesji, nie „na żywo”.
* **Duża moc i optymalizacja** – świetny do produkcji i rozproszonych obliczeń, ale trudniejszy dla początkujących.

### TensorFlow 2.x (od 2019)

* **Domyślnie „eager execution”** – działa podobnie jak PyTorch: obliczenia wykonywane są natychmiast.
* **Keras w centrum** – `tf.keras` stał się oficjalnym, wysokopoziomowym API do budowania i trenowania modeli.
* **Lepsza integracja z Pythonem** – można pisać kod z `if`, `for`, itp. (dynamiczny graf).
* **Zachowane tryby statyczne** – dzięki `@tf.function` można nadal „zamrozić” graf i uzyskać optymalizację w produkcji.
* **Łatwiejsza nauka i migracja** – kod jest krótszy, czytelniejszy, bardziej intuicyjny.



## Keras

Keras to tak naprawdę **wysokopoziomowe API** (interfejs) do budowania i trenowania sieci neuronowych w Pythonie.

🔹 **Krótko historycznie:**

* Powstał w **2015 roku**, autor: **François Chollet** (inżynier Google, twórca też frameworka `Xception`).
* Początkowo działał jako „nakładka” na różne backendy (np. TensorFlow, Theano, CNTK).
* Od **TensorFlow 2.0** Keras został wbudowany w TensorFlow jako **tf.keras** i stał się jego oficjalnym API.

---

### Po co jest Keras?

* Upraszcza tworzenie modeli: zamiast pisać dziesiątki linijek kodu, można w kilku krokach zbudować i wytrenować sieć neuronową.
* Ukrywa szczegóły techniczne (np. graf obliczeń, zarządzanie sesjami, optymalizację GPU).
* Jest intuicyjny – modele buduje się prawie jak z klocków Lego.

---

### Główne cechy Keras:

1. **Prostota** – łatwy start dla początkujących.
2. **Czytelność** – kod przypomina zwykły Python, a nie niszowy DSL.
3. **Elastyczność** – mimo prostoty, można też tworzyć bardzo złożone modele.
4. **Integracja z TensorFlow** – korzysta z jego mocy obliczeniowej (GPU/TPU, rozproszone trenowanie).

---

### Przykład – sieć klasyfikująca cyfry (MNIST)

```python
import tensorflow as tf
from tensorflow.keras import layers, models

# Model sekwencyjny
model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),    # wejście 28x28
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Kompilacja modelu
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Trenowanie
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))
```

✅ W kilkunastu linijkach mamy kompletny proces trenowania.
Gdyby pisać to od zera w „czystym” TensorFlow albo PyTorch – zajęłoby znacznie więcej kodu.

```python
import tensorflow as tf

# Dane
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# --- Definicja parametrów (ręcznie) ---
W1 = tf.Variable(tf.random.normal([784, 128]))
b1 = tf.Variable(tf.zeros([128]))
W2 = tf.Variable(tf.random.normal([128, 10]))
b2 = tf.Variable(tf.zeros([10]))

# --- Funkcja forward ---
def model(x):
    x = tf.reshape(x, [-1, 784])                  # flatten
    h = tf.nn.relu(tf.matmul(x, W1) + b1)         # warstwa ukryta
    y = tf.nn.softmax(tf.matmul(h, W2) + b2)      # wyjście
    return y

# --- Funkcja straty ---
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()

# --- Optymalizator ---
optimizer = tf.keras.optimizers.Adam()

# --- Pętla treningowa ---
for epoch in range(5):
    for i in range(len(x_train)):
        x = x_train[i:i+1]
        y_true = y_train[i:i+1]

        with tf.GradientTape() as tape:
            y_pred = model(x)
            loss = loss_fn(y_true, y_pred)

        grads = tape.gradient(loss, [W1, b1, W2, b2])
        optimizer.apply_gradients(zip(grads, [W1, b1, W2, b2]))

    print(f"Epoch {epoch+1}, Loss: {loss.numpy():.4f}")

```

👉 W skrócie: **Keras = przyjazna, prosta nakładka na TensorFlow**, która sprawia, że praca z sieciami neuronowymi jest szybsza i łatwiejsza.



/## 1. TensorFlow vs PyTorch

| Cecha                               | **TensorFlow**                                                                                       | **PyTorch**                                                            |
| ----------------------------------- | ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| **Rok powstania**                   | 2015 (Google Brain)                                                                                  | 2016 (Facebook AI Research)                                            |
| **Graf obliczeń**                   | TF1: statyczny graf; TF2: domyślnie dynamiczny (eager), z opcją kompilacji do grafu (`@tf.function`) | Zawsze dynamiczny graf (budowany w trakcie wykonywania kodu)           |
| **Produkcja / wdrażanie**           | Bardzo mocny ekosystem: TensorFlow Serving, TF Lite, TF.js                                           | TorchServe, TorchScript, ONNX – dobre, ale mniej dopracowane niż TF    |
| **Społeczność**                     | Duże wsparcie przemysłowe (Google, firmy używające TF w chmurze)                                     | Popularniejszy w środowisku akademickim i badawczym                    |
| **Uczenie rozproszone / wydajność** | Bardzo rozwinięte, integracja z TPU                                                                  | Bardzo dobre wsparcie GPU, integracja z CUDA, ostatnio też z Apple MPS |
| **Krzywa nauki**                    | TF1 – trudna, TF2/Keras – łatwa                                                                      | Bardzo intuicyjna, świetna do nauki i eksperymentów                    |

👉 Podsumowanie:

* **TensorFlow** – świetny do **produkcji, dużych wdrożeń i skalowalności**.
* **PyTorch** – idealny do **badań, eksperymentów i prototypowania**.

---

# 2. Keras vs PyTorch

| Cecha              | **Keras (tf.keras)**                                                                      | **PyTorch**                                                                          |
| ------------------ | ----------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| **Filozofia**      | Prosta, wysoki poziom, „modele z klocków Lego”                                            | Bardziej niskopoziomowy, ale elastyczny                                              |
| **Łatwość startu** | Bardzo łatwy – parę linijek i masz sieć                                                   | Prosty, ale wymaga jawnego pisania pętli treningowej                                 |
| **Elastyczność**   | Ograniczona – do typowych modeli (ale można pisać własne warstwy, trudniej niż w PyTorch) | Bardzo elastyczny – łatwo tworzyć nietypowe architektury, dynamiczne zmiany w modelu |
| **Debugowanie**    | Działa w TF eager mode, ale bywa „ukryty” poziom                                          | Bardzo przejrzyste debugowanie (graf tworzony w trakcie)                             |
| **Ekosystem**      | Wbudowane narzędzia TensorFlow (Lite, Serving, TPU)                                       | TorchVision, TorchText, TorchAudio, ONNX – mocne, ale mniej zunifikowane             |
| **Dla kogo**       | Początkujący, szybkie prototypowanie, projekty produkcyjne Google Cloud                   | Badacze, osoby chcące pełnej kontroli i eksperymentowania                            |

👉 Podsumowanie:

* **Keras** = prostota, szybkie budowanie klasycznych modeli.
* **PyTorch** = pełna kontrola i elastyczność, nawet kosztem większej ilości kodu.
* **TensorFlow**  = duża wydajność, świetny na produkcję
---



# Podstawy TensorFlow – Tensory

W tej sekcji omówimy:

* Konwersję tablic NumPy na tensory TensorFlow
* Tworzenie tensorów od zera* Różnice względem podejścia w PyTorch

## Wykonaj standardowe importy

In [2]:
import tensorflow as tf
import numpy as np

## Sprawdź wersję TensorFlow

TensorFlow 2 domyślnie uruchamia obliczenia w trybie eager, więc operacje działają podobnie jak w PyTorch.

In [3]:
print(tf.__version__)

2.20.0


## Konwersja tablic NumPy na tensory TensorFlow

Analogicznie do `torch.tensor`, w TensorFlow używamy m.in. `tf.convert_to_tensor` lub `tf.constant`.

Zauważ, że TensorFlow domyślnie tworzy tensory typu `tf.int64` dla liczb całkowitych i `tf.float32` dla wartości zmiennoprzecinkowych.

In [4]:
arr = np.arange(6)
x = tf.convert_to_tensor(arr)
print(x)
print('dtype:', x.dtype)
print('Jako NumPy:', x.numpy())

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int64)
dtype: <dtype: 'int64'>
Jako NumPy: [0 1 2 3 4 5]


W przeciwieństwie do PyTorch, tensory TensorFlow są niemodyfikowalne (**immutable**).

Zmiana tablicy źródłowej NumPy nie wpływa na tensor.

In [5]:
arr[0] = 999

print('Zmodyfikowane arr:', arr)

print('Tensor x pozostał bez zmian:', x.numpy())

Zmodyfikowane arr: [999   1   2   3   4   5]
Tensor x pozostał bez zmian: [0 1 2 3 4 5]


## TensorFlow Variables

Jeśli potrzebujemy obiektu, który można modyfikować "w miejscu", używamy `tf.Variable`.

To różnica względem PyTorch, gdzie każdy tensor może przechowywać gradienty.

In [6]:
var = tf.Variable([1., 2., 3.], dtype=tf.float32)
print(var)
var.assign_add([0.5, 0.5, 0.5])
print('Po assign_add:', var)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
Po assign_add: <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1.5, 2.5, 3.5], dtype=float32)>


## Tworzenie tensorów od zera

Odpowiedniki funkcji `torch.zeros` czy `torch.ones` znajdują się w module `tf`.

In [7]:
zeros = tf.zeros((2, 3))
ones = tf.ones((2, 3), dtype=tf.float32)
full = tf.fill((2, 3), 7)
print('zeros:', zeros.numpy())
print('ones:', ones.numpy())
print('fill:', full.numpy())

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
fill: [[7 7 7]
 [7 7 7]]


## Losowe liczby

TensorFlow udostępnia metody `tf.random.normal`, `tf.random.uniform` i wiele innych.

Nazwy są nieco inne niż w PyTorch, ale działanie jest analogiczne.

In [8]:
normal = tf.random.normal((2, 3), mean=0.0, stddev=1.0)
uniform = tf.random.uniform((2, 3), minval=-1, maxval=1)
print('Normalny rozkład:', normal.numpy())
print('Jednostajny rozkład:', uniform.numpy())

Normalny rozkład: [[-0.5798222   1.7611403  -0.09943233]
 [ 1.3010058   0.28214836  0.8640877 ]]
Jednostajny rozkład: [[ 0.06529355  0.01903343  0.3020897 ]
 [-0.572804   -0.9006293   0.7291479 ]]


## Konwersja typów danych

Do zmiany typu używamy `tf.cast`. To odpowiednik `tensor.type()` lub `tensor.to()` w PyTorch.

In [9]:
x_float = tf.constant([1, 2, 3], dtype=tf.int32)
x_float = tf.cast(x_float, tf.float32)
print(x_float)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


### Świetna robota!