In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.8.0'

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr.dtype

dtype('int64')

In [5]:
t = torch.from_numpy(arr)

In [11]:
torch.as_tensor(arr)

tensor([10,  2,  3,  4,  5])

In [7]:
arr[0] = 10

In [8]:
arr

array([10,  2,  3,  4,  5])

In [10]:
t


tensor([10,  2,  3,  4,  5])

In [12]:
torch.tensor(arr)

tensor([10,  2,  3,  4,  5])

In [20]:
arr[0] = 19

In [15]:
t

tensor([9, 2, 3, 4, 5])

In [18]:
t=torch.Tensor(arr)

In [21]:
t, arr

(tensor([1., 2., 3., 4., 5.]), array([19,  2,  3,  4,  5]))

In [22]:
torch.LongTensor(arr)

tensor([19,  2,  3,  4,  5])

In [24]:
torch.FloatTensor(arr)

tensor([19.,  2.,  3.,  4.,  5.])

In [27]:
torch.empty(4, 3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.zeros(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

empty
zeros

ones
eye

In [29]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
torch.linspace(1, 10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [32]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [35]:
x = torch.rand(5,2)

In [36]:
x.type(torch.int64)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [49]:
torch.arange(1, 11).reshape(10, 1 )

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [ ]:
torch.manual_seed(100)

In [52]:
x.shape

torch.Size([5, 2])

## Indeksowanie i wycinanie
Wyodrębnianie konkretnych wartości z tensora działa tak samo jak w tablicach NumPy<br>
<img src='arrayslicing.png' width="500" style="display: inline-block"><br><br>
Źródło obrazu: https://scipy-lectures.org/_images/numpy_indexing.png

Na początek utwórzmy taki tensor:

In [53]:
row0 = torch.arange(6)

In [54]:
row0

tensor([0, 1, 2, 3, 4, 5])

In [56]:
a = row0 + row0.reshape(6, -1) * 10

In [57]:
a[0, 3:5]

tensor([3, 4])

In [58]:
a[4:, 4:]

tensor([[44, 45],
        [54, 55]])

In [59]:
a + a

tensor([[  0,   2,   4,   6,   8,  10],
        [ 20,  22,  24,  26,  28,  30],
        [ 40,  42,  44,  46,  48,  50],
        [ 60,  62,  64,  66,  68,  70],
        [ 80,  82,  84,  86,  88,  90],
        [100, 102, 104, 106, 108, 110]])

In [60]:
result = torch.empty(3)

In [61]:
a = torch.tensor([1, 2, 3])
b = a + 1

In [62]:
torch.add(a, b, out=result)

tensor([3., 5., 7.])

In [63]:
result

tensor([3., 5., 7.])