In [1]:
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
arr = np.arange(6)

In [4]:
x = tf.convert_to_tensor(arr)

In [5]:
x

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5])>

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[0] = 11

In [8]:
x

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5])>

In [9]:
var = tf.Variable(arr)

In [12]:
var

<tf.Variable 'Variable:0' shape=(6,) dtype=int64, numpy=array([10,  1,  2,  3,  4,  5])>

In [15]:
var.assign_add([1, 2, 3, 4, 5, 6])

<tf.Variable 'UnreadVariable' shape=(6,) dtype=int64, numpy=array([11,  3,  5,  7,  9, 11])>

In [16]:
var

<tf.Variable 'Variable:0' shape=(6,) dtype=int64, numpy=array([11,  3,  5,  7,  9, 11])>

In [17]:
tf.zeros((2, 5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
tf.ones

<function tensorflow.python.ops.array_ops.ones(shape, dtype=tf.float32, name=None, layout=None)>

In [19]:
tf.fill((2, 3), 7)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7]], dtype=int32)>

In [20]:
tf.random.normal((2, 3), mean=0, stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.3625607 , -1.0657073 ,  0.16775946],
       [-1.4790335 ,  0.62134415, -0.24659806]], dtype=float32)>

In [22]:
tf.random.uniform((2, 3), minval=0, maxval=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.58193636, 0.5861279 , 0.7914907 ],
       [0.91201425, 0.84249353, 0.6338619 ]], dtype=float32)>

In [23]:
x_float = tf.random.uniform((2, 3), minval=0, maxval=1)

In [24]:
x_float = tf.cast(x_float, tf.int32)

In [25]:
x_float

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [26]:


row_0 = tf.range(6)
row_0

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

In [27]:
matrix = row_0 + tf.expand_dims(row_0, 1) * 10
matrix

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]], dtype=int32)>

In [28]:
matrix[0, 3:5]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [29]:
matrix[4:, 4:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[44, 45],
       [54, 55]], dtype=int32)>

In [30]:
tf.reshape(matrix, (3, 12))

<tf.Tensor: shape=(3, 12), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25, 30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45, 50, 51, 52, 53, 54, 55]], dtype=int32)>

In [33]:
row_0 + row_0

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10], dtype=int32)>

In [35]:
x = tf.reshape(matrix, (3, 12))

In [38]:
x @ tf.transpose(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1010,  2810,  4610],
       [ 2810,  9410, 16010],
       [ 4610, 16010, 27410]], dtype=int32)>

In [39]:
file_path = "Data/iris.csv"

dataset = tf.data.experimental.make_csv_dataset(
    file_path,
    batch_size=16,
    label_name="target",
    num_epochs=2,
    shuffle=True
)

dataset

<_PrefetchDataset element_spec=(OrderedDict({'sepal length (cm)': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'sepal width (cm)': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'petal length (cm)': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'petal width (cm)': TensorSpec(shape=(None,), dtype=tf.float32, name=None)}), TensorSpec(shape=(None,), dtype=tf.float32, name=None))>

In [46]:
for f, l in dataset.take(2):
    print("xxx")
    # print(f.shape, l.shape)
    print(l)

xxx
tf.Tensor([2. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 2. 1. 1.], shape=(16,), dtype=float32)
xxx
tf.Tensor([2. 1. 0. 2. 0. 0. 1. 2. 2. 1. 0. 1. 1. 1. 2. 0.], shape=(16,), dtype=float32)


2025-10-04 16:47:32.664694: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [47]:
import pandas as pd

# Wczytanie Pandasem
df = pd.read_csv("Data/iris.csv")
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [48]:
X = df.drop("target", axis=1).values
y = df["target"].astype("category").cat.codes.values  # zamiana na liczby

# Konwersja do tensora
X_tensor = tf.convert_to_tensor(X, dtype=tf.float32)
y_tensor = tf.convert_to_tensor(y, dtype=tf.int32)

In [49]:
y_tensor

<tf.Tensor: shape=(150,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)>

In [51]:
from tensorflow import keras

In [50]:
(X_train, y_train), (X_test, y_test) = keras.datasets.iris.load()

AttributeError: module 'keras.datasets' has no attribute 'iris'

In [52]:
dir(keras.datasets)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'boston_housing',
 'california_housing',
 'cifar10',
 'cifar100',
 'fashion_mnist',
 'imdb',
 'mnist',
 'reuters']