## PyTorch

<img src='https://pytorch.org/wp-content/uploads/2024/10/logo.svg' width=400>

https://pytorch.org/

**PyTorch** to jedna z najpopularniejszych bibliotek do uczenia maszynowego i głębokiego uczenia (deep learning). Jest napisana w języku **Python** z wydajnym backendem w **C++**. Powstała w 2016 roku w laboratoriach **Facebook AI Research (FAIR)** jako bardziej elastyczna alternatywa dla wcześniejszych frameworków, takich jak Torch czy TensorFlow.

### Kluczowe cechy

* **Dynamiczne grafy obliczeń** – w przeciwieństwie do starszych bibliotek (np. TensorFlow 1.x), PyTorch buduje graf obliczeń w locie. Ułatwia to debugowanie i eksperymentowanie z modelami.
    👉 Czyli w praktyce: dynamiczny graf to taka „tablica wyników”, którą PyTorch tworzy na bieżąco, zapisując jak powstawały kolejne wartości, żeby potem umieć policzyć gradienty do uczenia.
* **Autograd** – wbudowany mechanizm automatycznego różniczkowania, który pozwala łatwo liczyć gradienty potrzebne w algorytmach optymalizacji.
* **Integracja z ekosystemem Pythona** – PyTorch dobrze współpracuje z bibliotekami naukowymi jak NumPy, SciPy czy scikit-learn.
* **Wsparcie GPU** – operacje mogą być łatwo przenoszone na procesory graficzne (CUDA), co znacznie przyspiesza trenowanie dużych sieci neuronowych.

### Do czego jest używany?

* **Uczenie maszynowe i głębokie uczenie** – budowa sieci neuronowych, trenowanie modeli klasyfikacji, regresji, generatywnych sieci adversarialnych (GAN).
* **Wizja komputerowa** – rozpoznawanie obrazów, detekcja obiektów, segmentacja semantyczna (często z wykorzystaniem rozszerzenia **torchvision**).
* **Przetwarzanie języka naturalnego (NLP)** – tłumaczenie maszynowe, analiza sentymentu, modele językowe (transformery, LSTM).
* **Badania naukowe** – dzięki elastyczności PyTorch jest chętnie wybierany przez środowisko akademickie do testowania nowych architektur.
* **Produkcja** – z narzędziami jak **TorchScript** czy **PyTorch Lightning** ułatwia wdrażanie modeli do środowisk produkcyjnych.

### Dlaczego zyskał popularność?

PyTorch stał się standardem w środowisku badawczym, ponieważ łączy łatwość użycia z dużą mocą obliczeniową. Wiele współczesnych przełomowych modeli AI (np. GPT, BERT, Stable Diffusion) powstało z jego wykorzystaniem.

Przygodę z PyTorch zaczniemy od podstaw - czyli pracy z tensorami.


# Podstawy Tensorów
W tej sekcji omówimy:
* Konwersję tablic NumPy na tensory PyTorch
* Tworzenie tensorów od zera

## Wykonaj standardowe importy


In [1]:
import torch
import numpy as np

Sprawdźmy wersję PyTorch. Materiały są na 2.8.0

In [4]:
torch.__version__

'2.8.0'

## Konwersja tablic NumPy na tensory PyTorch
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor</tt></strong></a> to wielowymiarowa macierz zawierająca elementy jednego typu danych.<br>
Obliczenia na tensorach można wykonywać tylko wtedy, gdy mają one ten sam dtype.<br>
W niektórych przypadkach tensory zastępują tablice NumPy, aby wykorzystać moc GPU (więcej o tym później).


In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [6]:
x = torch.from_numpy(arr)
# Odpowiada funkcji x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5])


In [7]:
# Wypisz typ danych przechowywanych przez tensor
print(x.dtype)

torch.int64


In [8]:
# Wypisz typ obiektu tensora
print(type(x))
print(x.type()) # bardziej szczegółowa informacja

<class 'torch.Tensor'>
torch.LongTensor


In [9]:
arr2 = np.arange(0.,12.).reshape(4,3)
print(arr2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [10]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


Tutaj <tt>torch.DoubleTensor</tt> oznacza 64-bitowe liczby zmiennoprzecinkowe.


<h2><a href='https://pytorch.org/docs/stable/tensors.html'>Typy danych tensorów</a></h2>
<table style="display: inline-block">
<tr><th>TYP</th><th>NAZWA</th><th>ODPOWIEDNIK</th><th>TYP TENSORA</th></tr>
<tr><td>32-bitowa liczba całkowita (ze znakiem)</td><td>torch.int32</td><td>torch.int</td><td>IntTensor</td></tr>
<tr><td>64-bitowa liczba całkowita (ze znakiem)</td><td>torch.int64</td><td>torch.long</td><td>LongTensor</td></tr>
<tr><td>16-bitowa liczba całkowita (ze znakiem)</td><td>torch.int16</td><td>torch.short</td><td>ShortTensor</td></tr>
<tr><td>32-bitowa liczba zmiennoprzecinkowa</td><td>torch.float32</td><td>torch.float</td><td>FloatTensor</td></tr>
<tr><td>64-bitowa liczba zmiennoprzecinkowa</td><td>torch.float64</td><td>torch.double</td><td>DoubleTensor</td></tr>
<tr><td>16-bitowa liczba zmiennoprzecinkowa</td><td>torch.float16</td><td>torch.half</td><td>HalfTensor</td></tr>
<tr><td>8-bitowa liczba całkowita (ze znakiem)</td><td>torch.int8</td><td></td><td>CharTensor</td></tr>
<tr><td>8-bitowa liczba całkowita (bez znaku)</td><td>torch.uint8</td><td></td><td>ByteTensor</td></tr></table>


## Kopiowanie a współdzielenie pamięci


<a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a><br>

Istnieje wiele funkcji do <a href='https://pytorch.org/docs/stable/torch.html#creation-ops'>tworzenia tensorów</a>. Przy korzystaniu z <a href='https://pytorch.org/docs/stable/torch.html#torch.from_numpy'><strong><tt>torch.from_numpy()</tt></strong></a> oraz <a href='https://pytorch.org/docs/stable/torch.html#torch.as_tensor'><strong><tt>torch.as_tensor()</tt></strong></a> tensor PyTorch i źródłowa tablica NumPy współdzielą tę samą pamięć. Oznacza to, że zmiany w jednym obiekcie wpływają na drugi. Z kolei funkcja <a href='https://pytorch.org/docs/stable/torch.html#torch.tensor'><strong><tt>torch.tensor()</tt></strong></a> zawsze tworzy kopię.


In [11]:
# Korzystając z torch.from_numpy()
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [12]:
arr[2]=77
print(t)

tensor([ 0,  1, 77,  3,  4])


In [13]:
# Korzystając z torch.tensor()
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4])


In [14]:
arr[2]=77
print(t)

tensor([0, 1, 2, 3, 4])


## Konstruktory klas
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.Tensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.FloatTensor()</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/tensors.html'><strong><tt>torch.LongTensor()</tt></strong></a> itd.<br>

Istnieje subtelna różnica między użyciem funkcji fabrykującej <font color=black><tt>torch.tensor(data)</tt></font> a konstruktorem klasy <font color=black><tt>torch.Tensor(data)</tt></font>.<br>
Funkcja fabrykująca określa dtype na podstawie danych wejściowych lub przekazanego argumentu dtype.<br>
Konstruktor klasy <tt>torch.Tensor()</tt> jest po prostu aliasem <tt>torch.FloatTensor(data)</tt>. Rozważ przykład poniżej:


In [15]:
data = np.array([1,2,3])

In [16]:
a = torch.Tensor(data)  # To samo co cc = torch.FloatTensor(data)
print(a, a.type())

tensor([1., 2., 3.]) torch.FloatTensor


In [17]:
b = torch.tensor(data)
print(b, b.type())

tensor([1, 2, 3]) torch.LongTensor


In [18]:
c = torch.tensor(data, dtype=torch.long)
print(c, c.type())

tensor([1, 2, 3]) torch.LongTensor


## Tworzenie tensorów od zera
### Tenseory niezainicjalizowane – <tt>.empty()</tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.empty'><strong><tt>torch.empty()</tt></strong></a> zwraca <em>niezainicjalizowany</em> tensor. Przydzielany jest blok pamięci o zadanym rozmiarze, a zwracane są wartości już w nim istniejące. To zachowanie podobne do <tt>numpy.empty()</tt>.


In [19]:
x = torch.empty(4, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Tensory zainicjalizowane – <tt>.zeros()</tt> i <tt>.ones()</tt>
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros'><strong><tt>torch.zeros(size)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones'><strong><tt>torch.ones(size)</tt></strong></a><br>
Warto od razu przekazać docelowy dtype.


In [20]:
x = torch.zeros(4, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Tensory z zakresów
<a href='https://pytorch.org/docs/stable/torch.html#torch.arange'><strong><tt>torch.arange(start,end,step)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.linspace'><strong><tt>torch.linspace(start,end,steps)</tt></strong></a><br>
Zwróć uwagę, że dla <tt>.arange()</tt> parametr <tt>end</tt> jest wyłączny, a dla <tt>linspace()</tt> – włączny.


In [21]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [22]:
x = torch.linspace(0,18,12).reshape(3,4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


### Tensory z danych
<tt>torch.tensor()</tt> dobiera dtype na podstawie przekazanych danych:


In [24]:
x = torch.tensor([1, 2, 3, 4])
print(x)
print(x.dtype)
print(x.type())

tensor([1, 2, 3, 4])
torch.int64
torch.LongTensor


Alternatywnie możesz ustawić typ przez użycie odpowiedniej metody tensora. Listę typów znajdziesz na https://pytorch.org/docs/stable/tensors.html


In [25]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)
print(x.type())

tensor([5., 6., 7.])
torch.float32
torch.FloatTensor


Możesz też przekazać dtype jako argument. Listę typów odwiedź na https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.dtype<br>


In [26]:
x = torch.tensor([8,9,-3], dtype=torch.int)
print(x)
print(x.dtype)
print(x.type())

tensor([ 8,  9, -3], dtype=torch.int32)
torch.int32
torch.IntTensor


### Zmiana dtype istniejących tensorów



Zamiast tego użyj metody tensora <tt>.type()</tt>.


In [29]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.LongTensor
New: torch.LongTensor


### Tensory liczb losowych
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand'><strong><tt>torch.rand(size)</tt></strong></a> zwraca próbki z rozkładu jednostajnego [0, 1)<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn'><strong><tt>torch.randn(size)</tt></strong></a> zwraca próbki z „rozkładu normalnego standardowego” [σ = 1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;W przeciwieństwie do <tt>rand</tt>, który jest jednostajny, wartości bliższe zeru pojawiają się częściej.<br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint'><strong><tt>torch.randint(low,high,size)</tt></strong></a> zwraca losowe liczby całkowite od low (włącznie) do high (wyłącznie)


In [30]:
x = torch.rand(4, 3)
print(x)

tensor([[0.2086, 0.2178, 0.5634],
        [0.9520, 0.5795, 0.6904],
        [0.5256, 0.3876, 0.1220],
        [0.6504, 0.8402, 0.9002]])


In [31]:
x = torch.randn(4, 3)
print(x)

tensor([[ 1.0283,  1.3081, -0.0048],
        [-0.0164, -0.8525,  0.3178],
        [-1.0164,  0.9167, -0.0262],
        [-0.7695,  0.1847, -1.5231]])


In [32]:
x = torch.randint(0, 5, (4, 3))
print(x)

tensor([[3, 0, 3],
        [2, 4, 3],
        [1, 1, 4],
        [4, 4, 4]])


### Losowe tensory dopasowane rozmiarem do wejścia
<a href='https://pytorch.org/docs/stable/torch.html#torch.rand_like'><strong><tt>torch.rand_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randn_like'><strong><tt>torch.randn_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.randint_like'><strong><tt>torch.randint_like(input,low,high)</tt></strong></a><br>
te funkcje zwracają losowe tensory o tym samym rozmiarze co <tt>input</tt>


In [33]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [34]:
x2 = torch.randn_like(x)
print(x2)

tensor([[-0.0137, -1.6785, -0.7495, -0.6323,  0.7244],
        [ 0.4662, -0.7840, -0.0950, -0.6049, -0.0056]])


Tego samego zapisu można użyć z
<a href='https://pytorch.org/docs/stable/torch.html#torch.zeros_like'><strong><tt>torch.zeros_like(input)</tt></strong></a><br>
<a href='https://pytorch.org/docs/stable/torch.html#torch.ones_like'><strong><tt>torch.ones_like(input)</tt></strong></a>


In [35]:
x3 = torch.ones_like(x2)
print(x3)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### Ustawienie ziarna losowego
<a href='https://pytorch.org/docs/stable/torch.html#torch.manual_seed'><strong><tt>torch.manual_seed(int)</tt></strong></a> służy do uzyskiwania powtarzalnych rezultatów.


In [36]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [37]:
torch.manual_seed(42)
x = torch.rand(2, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


## Atrybuty tensora
Poza <tt>dtype</tt> możemy sprawdzić inne <a href='https://pytorch.org/docs/stable/tensor_attributes.html'>atrybuty tensora</a>, takie jak <tt>shape</tt>, <tt>device</tt> i <tt>layout</tt>.


In [38]:
x.shape

torch.Size([2, 3])

In [39]:
x.size()  # to samo co x.shape

torch.Size([2, 3])

In [40]:
x.device

device(type='cpu')

PyTorch obsługuje wiele <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch-device'>urządzeń</a>, wykorzystując moc jednego lub wielu GPU oprócz CPU. Nie będziemy tego tutaj zgłębiać, ale wiedz, że operacje między tensorami są możliwe tylko wtedy, gdy znajdują się na tym samym urządzeniu.


In [41]:
x.layout

torch.strided

PyTorch posiada klasę przechowującą informacje o <a href='https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.layout'>układzie pamięci</a>. Domyślne ustawienie <a href='https://en.wikipedia.org/wiki/Stride_of_an_array'>strided</a> w pełni nam wystarczy w tym kursie.


### Super! W kolejnym module przyjrzymy się operacjon na tensorach.
