# Ćwiczenia z podstaw PyTorcha
W tych zadaniach utworzymy tensor i wykonamy na nim kilka operacji.

<div class="alert alert-danger" style="margin: 10px"><strong>WAŻNA UWAGA!</strong> Nie uruchamiaj komórek znajdujących się bezpośrednio nad przykładowymi wynikami,<br>w przeciwnym razie nadpiszesz pokazane rozwiązania!</div>


### 1. Wykonaj standardowe importy
Zaimportuj torch oraz NumPy.


In [1]:
# KOD TUTAJ



### 2. Ustaw ziarno losowe NumPy i PyTorch na wartość „42”
Dzięki temu będziemy otrzymywać te same „losowe” wyniki.


In [2]:
# KOD TUTAJ



### 3. Utwórz tablicę NumPy „arr” zawierającą 6 losowych liczb całkowitych z zakresu [0, 5)


In [ ]:
# KOD TUTAJ



In [3]:
# NIE PISZ TUTAJ

[3 4 2 4 4 1]


### 4. Utwórz tensor „x” z powyższej tablicy


In [ ]:
# KOD TUTAJ



In [4]:
# NIE PISZ TUTAJ

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Zmień dtype tensora x z 'int32' na 'int64'
Uwaga: 'int64' to również 'LongTensor'.


In [ ]:
# KOD TUTAJ



In [5]:
# NIE PISZ TUTAJ

torch.LongTensor


### 6. Przekształć x do tensora 3x2
Można to zrobić na kilka sposobów.


In [ ]:
# KOD TUTAJ



In [6]:
# NIE PISZ TUTAJ

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Zwróć prawą kolumnę tensora x


In [ ]:
# KOD TUTAJ



In [7]:
# NIE PISZ TUTAJ

tensor([[4],
        [4],
        [1]])


### 8. Nie zmieniając x, zwróć tensor z kwadratami jego wartości
Można to zrobić na kilka sposobów.


In [ ]:
# KOD TUTAJ



In [8]:
# NIE PISZ TUTAJ

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Utwórz tensor „y” z taką samą liczbą elementów jak x, umożliwiający mnożenie macierzy z x
Użyj bezpośrednio PyTorcha (nie NumPy), aby stworzyć tensor losowych liczb całkowitych z zakresu [0, 5).<br>
Zastanów się, jaki kształt musi mieć tensor, aby mnożenie macierzy było możliwe.


In [ ]:
# KOD TUTAJ



In [9]:
# NIE PISZ TUTAJ

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Znajdź iloczyn macierzowy tensorów x i y


In [ ]:
# KOD TUTAJ



In [10]:
# NIE PISZ TUTAJ

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Świetna robota!
