# Ćwiczenia z podstaw PyTorcha – ROZWIĄZANIA
W tych zadaniach utworzymy tensor i wykonamy na nim kilka operacji.

<div class="alert alert-danger" style="margin: 10px"><strong>WAŻNA UWAGA!</strong> Nie uruchamiaj komórek znajdujących się bezpośrednio nad przykładowymi wynikami,<br>w przeciwnym razie nadpiszesz pokazane rozwiązania!</div>


### 1. Wykonaj standardowe importy
Zaimportuj torch oraz NumPy.


In [1]:
# KOD TUTAJ
import torch
import numpy as np

### 2. Ustaw ziarno losowe NumPy i PyTorch na wartość „42”
Dzięki temu będziemy otrzymywać te same „losowe” wyniki.


In [2]:
# KOD TUTAJ
np.random.seed(42)
torch.manual_seed(42);  # średnik ukrywa linijkę wyjściową w Jupyterze

### 3. Utwórz tablicę NumPy „arr” zawierającą 6 losowych liczb całkowitych z zakresu [0, 5)


In [3]:
# KOD TUTAJ



In [4]:
# NIE PISZ TUTAJ
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


### 4. Utwórz tensor „x” z powyższej tablicy


In [5]:
# KOD TUTAJ



In [6]:
# NIE PISZ TUTAJ
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1])


### 5. Zmień dtype tensora x z 'int32' na 'int64'
Uwaga: 'int64' to również 'LongTensor'.


In [7]:
# KOD TUTAJ



In [8]:
# NIE PISZ TUTAJ
x = x.type(torch.int64)
# x = x.type(torch.LongTensor)
print(x.type())

torch.LongTensor


### 6. Przekształć x do tensora 3x2
Można to zrobić na kilka sposobów.


In [9]:
# KOD TUTAJ



In [10]:
# NIE PISZ TUTAJ
x = x.view(3,2)
# x = x.reshape(3,2)
# x.resize_(3,2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Zwróć prawą kolumnę tensora x


In [11]:
# KOD TUTAJ



In [12]:
# NIE PISZ TUTAJ
print(x[:,1:])
# print(x[:,1])

tensor([[4],
        [4],
        [1]])


### 8. Nie zmieniając x, zwróć tensor z kwadratami jego wartości
Można to zrobić na kilka sposobów.


In [13]:
# KOD TUTAJ



In [14]:
# NIE PISZ TUTAJ
print(x*x)
# print(x**2)
# print(x.mul(x))
# print(x.pow(2))
# print(torch.mul(x,x))

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Utwórz tensor „y” z taką samą liczbą elementów jak x, umożliwiający mnożenie macierzy z x
Użyj bezpośrednio PyTorcha (nie NumPy), aby stworzyć tensor losowych liczb całkowitych z zakresu [0, 5).<br>
Zastanów się, jaki kształt musi mieć tensor, aby mnożenie macierzy było możliwe.


In [17]:
# KOD TUTAJ



In [18]:
# NIE PISZ TUTAJ
y = torch.randint(0,5,(2,3))
print(y)

tensor([[0, 4, 0],
        [3, 3, 4]])


### 10. Znajdź iloczyn macierzowy tensorów x i y


In [21]:
# KOD TUTAJ

x @ y

tensor([[12, 24, 16],
        [12, 20, 16],
        [ 3, 19,  4]])

In [20]:
# NIE PISZ TUTAJ
print(x.mm(y))

tensor([[12, 24, 16],
        [12, 20, 16],
        [ 3, 19,  4]])


## Świetna robota!
