# Ćwiczenia z podstaw PyTorcha
W tych zadaniach utworzymy tensor i wykonamy na nim kilka operacji.

<div class="alert alert-danger" style="margin: 10px"><strong>WAŻNA UWAGA!</strong> Nie uruchamiaj komórek znajdujących się bezpośrednio nad przykładowymi wynikami,<br>w przeciwnym razie nadpiszesz pokazane rozwiązania!</div>


### 1. Wykonaj standardowe importy
Zaimportuj torch oraz NumPy.


In [1]:
# KOD TUTAJ
import torch
import numpy as np


In [4]:
x =1;y=2

### 2. Ustaw ziarno losowe NumPy i PyTorch na wartość „42”
Dzięki temu będziemy otrzymywać te same „losowe” wyniki.


In [8]:
# KOD TUTAJ
np.random.seed(100)
torch.manual_seed(100);


### 3. Utwórz tablicę NumPy „arr” zawierającą 6 losowych liczb całkowitych z zakresu [0, 5)


In [9]:
# KOD TUTAJ

arr = np.random.randint(0, 5, 6)
print(arr)

[0 0 3 0 2 4]


In [10]:
# NIE PISZ TUTAJ

### 4. Utwórz tensor „x” z powyższej tablicy


In [11]:
# KOD TUTAJ

x = torch.from_numpy(arr)
x

tensor([0, 0, 3, 0, 2, 4])

In [4]:
# NIE PISZ TUTAJ

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Zmień dtype tensora x z 'int32' na 'int64'
Uwaga: 'int64' to również 'LongTensor'.


In [15]:
# KOD TUTAJ
x.dtype
x = x.type(torch.int32)
x

tensor([0, 0, 3, 0, 2, 4], dtype=torch.int32)

In [5]:
# NIE PISZ TUTAJ

torch.LongTensor


### 6. Przekształć x do tensora 3x2
Można to zrobić na kilka sposobów.


In [17]:
# KOD TUTAJ
# x.reshape(3, 2)
x.view(3, 2)


tensor([[0, 0],
        [3, 0],
        [2, 4]], dtype=torch.int32)

In [6]:
# NIE PISZ TUTAJ

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Zwróć prawą kolumnę tensora x


In [19]:
# KOD TUTAJ

x = x.reshape(3,2)
x[:, -1:]

tensor([[0],
        [0],
        [4]], dtype=torch.int32)

In [7]:
# NIE PISZ TUTAJ

tensor([[4],
        [4],
        [1]])


### 8. Nie zmieniając x, zwróć tensor z kwadratami jego wartości
Można to zrobić na kilka sposobów.


In [21]:
# KOD TUTAJ
x ** 2, x


(tensor([[ 0,  0],
         [ 9,  0],
         [ 4, 16]], dtype=torch.int32),
 tensor([[0, 0],
         [3, 0],
         [2, 4]], dtype=torch.int32))

In [8]:
# NIE PISZ TUTAJ

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Utwórz tensor „y” z taką samą liczbą elementów jak x, umożliwiający mnożenie macierzy z x
Użyj bezpośrednio PyTorcha (nie NumPy), aby stworzyć tensor losowych liczb całkowitych z zakresu [0, 5).<br>
Zastanów się, jaki kształt musi mieć tensor, aby mnożenie macierzy było możliwe.


In [33]:
# KOD TUTAJ
y = torch.randint(0, 5, (3, 2))
y = y.type(torch.int32)

In [34]:
x.T

tensor([[0, 3, 2],
        [0, 0, 4]], dtype=torch.int32)

In [35]:
# NIE PISZ TUTAJ

### 10. Znajdź iloczyn macierzowy tensorów x i y


In [38]:
# KOD TUTAJ
x.T @ y


tensor([[18, 12],
        [12,  0]], dtype=torch.int32)

In [10]:
# NIE PISZ TUTAJ

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Świetna robota!
