# Ćwiczenia: Podstawy TensorFlow – Rozwiązania

Wykonaj poniższe zadania, aby utrwalić podstawowe operacje na tensorach TensorFlow.

<div class="alert alert-danger" style="margin: 10px"><strong>WAŻNA UWAGA!</strong> Nie uruchamiaj komórek znajdujących się bezpośrednio nad przykładowymi rozwiązaniami,<br>w przeciwnym razie nadpiszesz podpowiedzi!</div>


### 1. Wykonaj standardowe importy

### 2. Ustaw ziarno losowe TensorFlow i NumPy na wartość 42

### 3. Utwórz tablicę NumPy `arr` z 6 losowymi liczbami całkowitymi z zakresu [0,5)

array([3, 4, 2, 4, 4, 1])

### 4. Stwórz tensor `x` z tablicy `arr`

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([3, 4, 2, 4, 4, 1])>

### 5. Zmień dtype tensora `x` na `tf.float32`

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([3., 4., 2., 4., 4., 1.], dtype=float32)>

### 6. Ukształtuj tensor `x` do postaci 3x2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 4.],
       [2., 4.],
       [4., 1.]], dtype=float32)>

### 7. Zwróć prawą kolumnę tensora `x`

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 4., 1.], dtype=float32)>

### 8. Utwórz tensor kwadratów wartości `x`

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9., 16.],
       [ 4., 16.],
       [16.,  1.]], dtype=float32)>

### 9. Utwórz tensor `y` tak, aby można było wykonać mnożenie macierzy `x @ y`

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.3228106 , 2.2050338 , 1.7644125 ],
       [2.3224127 , 0.16830206, 3.4233618 ]], dtype=float32)>

### 10. Oblicz iloczyn macierzy `x` i `y`

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[19.258083 ,  7.2883096, 18.986685 ],
       [15.935272 ,  5.083276 , 17.222273 ],
       [15.613655 ,  8.988438 , 10.481012 ]], dtype=float32)>

## Świetna robota!